name: Deploy to Dev

on:
  push:
    branches:
      - Dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Dev Droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /home/appuser/frontend/Admin-dashboard
            git checkout Dev
            git pull origin Dev
            npm ci
            npm run build